# Generated by Django 5.2.4 on 2025-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchN', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='search_images/')),
                ('results', models.TextField()),
            ],
        ),
    ]
