# Generated by Django 5.2.4 on 2025-07-21 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchN', '0003_searchn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchn',
            old_name='query',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='searchn',
            name='image',
        ),
        migrations.RemoveField(
            model_name='searchn',
            name='results',
        ),
        migrations.AddField(
            model_name='searchn',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 21, 12, 51, 17, 55612, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchn',
            name='link',
            field=models.URLField(default='https://nhentai.net/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchn',
            name='url',
            field=models.URLField(default='https://t1.nhentai.net/galleries/2577863/thumb.jpg'),
            preserve_default=False,
        ),
    ]
