# Generated by Django 5.2.4 on 2025-07-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchN', '0004_rename_query_searchn_name_remove_searchn_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchn',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
