# Generated by Django 5.2.4 on 2025-07-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchN', '0005_searchn_is_remote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
