version: '3.9'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data_a:/data
    entrypoint: redis-server --appendonly yes
volumes:
  redis_data_a: